/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI.GUI_NHANVIEN;

/**
 *
 * @author SYN
 */
public class taikhoanJdialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public taikhoanJdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTTCT = new javax.swing.JLabel();
        jLabelThemTK = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabelMaNV = new javax.swing.JLabel();
        jTextFieldMaNV = new javax.swing.JTextField();
        jLabelTK = new javax.swing.JLabel();
        jTextFieldTK = new javax.swing.JTextField();
        jLabelHieuLuc = new javax.swing.JLabel();
        jLabelVaiTro = new javax.swing.JLabel();
        jComboHieuLuc = new javax.swing.JComboBox<>();
        jComboVaiTro = new javax.swing.JComboBox<>();
        jPanelThem = new javax.swing.JPanel();
        jButtonThem = new javax.swing.JButton();
        jPanelUpdate = new javax.swing.JPanel();
        jButtonSua = new javax.swing.JButton();
        jLabelThongBao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết nhân viên");
        setIconImage(null);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelTTCT.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabelTTCT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTTCT.setText("THÔNG TIN CHI TIẾT TÀI KHOẢN");
        jLabelTTCT.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(15, 5, 0, 5);
        getContentPane().add(jLabelTTCT, gridBagConstraints);

        jLabelThemTK.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelThemTK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThemTK.setText("Thêm tài khoản");
        jLabelThemTK.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 14, 4);
        getContentPane().add(jLabelThemTK, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelMaNV.setText("Mã nhân viên");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jLabelMaNV, gridBagConstraints);

        jTextFieldMaNV.setEditable(false);
        jTextFieldMaNV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldMaNV.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jTextFieldMaNV, gridBagConstraints);

        jLabelTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelTK.setText("Tài khoản");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jLabelTK, gridBagConstraints);

        jTextFieldTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextFieldTK.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jTextFieldTK, gridBagConstraints);

        jLabelHieuLuc.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelHieuLuc.setText("Hiệu lực");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jLabelHieuLuc, gridBagConstraints);

        jLabelVaiTro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelVaiTro.setText("Vai trò");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jLabelVaiTro, gridBagConstraints);

        jComboHieuLuc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboHieuLuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tài khoản mở", "Tài khoản đóng" }));
        jComboHieuLuc.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jComboHieuLuc, gridBagConstraints);

        jComboVaiTro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboVaiTro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Manager", "Receptionist" }));
        jComboVaiTro.setPreferredSize(new java.awt.Dimension(400, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanel1.add(jComboVaiTro, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanelThem.setLayout(new java.awt.GridBagLayout());

        jButtonThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanelThem.add(jButtonThem, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 3.0;
        getContentPane().add(jPanelThem, gridBagConstraints);

        jPanelUpdate.setLayout(new java.awt.GridBagLayout());

        jButtonSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.setPreferredSize(new java.awt.Dimension(100, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        jPanelUpdate.add(jButtonSua, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jPanelUpdate, gridBagConstraints);

        jLabelThongBao.setForeground(new java.awt.Color(255, 51, 0));
        jLabelThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThongBao.setText("label để thông báo lỗi");
        jLabelThongBao.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jLabelThongBao, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JComboBox<String> jComboHieuLuc;
    private javax.swing.JComboBox<String> jComboVaiTro;
    private javax.swing.JLabel jLabelHieuLuc;
    private javax.swing.JLabel jLabelMaNV;
    private javax.swing.JLabel jLabelTK;
    private javax.swing.JLabel jLabelTTCT;
    private javax.swing.JLabel jLabelThemTK;
    private javax.swing.JLabel jLabelThongBao;
    private javax.swing.JLabel jLabelVaiTro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelThem;
    private javax.swing.JPanel jPanelUpdate;
    private javax.swing.JTextField jTextFieldMaNV;
    private javax.swing.JTextField jTextFieldTK;
    // End of variables declaration//GEN-END:variables
}
